version: '2.1'

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend.Dockerfile
    depends_on:
      - postgres
    restart: 'no'
    command: gunicorn -b 0.0.0.0:8000 -w=2 wsgi:app
    volumes:
      - ./backend/project:/app
      - blob:/media/files
    ports:
      - 8000:8000

  postgres:
    image: postgres:12.2
    env_file:
      - env.dev.env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 44312:5432

  migrator:
    build:
      context: .
      dockerfile: docker/migrator.Dockerfile
    depends_on:
      - postgres
    env_file:
      - env.dev.env
    restart: 'no'
    volumes:
      - ./backend/project/models/changelog:/liquibase/changelog

networks:
  default:
    driver: bridge

volumes:
  blob:
  postgres: